version: "3.9"

services:
  sftp-middleware:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3000
    ports:
      - "80:3000"
    volumes:
      - ./uploads:/usr/src/app/uploads
